# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Saul's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Saul Means
headline: New York, New York
description: | 
  I'm a Data Science Analyst at BNY, currently in a rotational program. I studied Data Science at Purdue University and am pursuing a Master's in Computer Science at Georgia Tech.
  
  I am very passionate about my work and I love tackling data challenges across the entire data stack.

  When I'm not debugging my past mistakes, you'll probably find me running through NYC or spending time with family and friends.  

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/saul_pp.png


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: /assets/resume/ErickSaulMeans_Resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: saulm24    # https://www.linkedin.com/in/saulm24
  github: itsSaul24    # https://github.com/itsSaul24
  medium:            # https://medium.com/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Programming Languages
    tools:
    - Python
    - SQL
    - R
    - Git
    - Java (Proficient)
    - JavaScript (Proficient)
  - category: Machine Learning & AI
    tools:
    - AI Agents
    - Large Language Models (LLMs)
    - Prompt Engineering
    - RAG (Retrieval-Augmented Generation)
    - NLP (Natural Language Processing
    - CNNs (Convolutional Neural Networks)
    - GNNs (Graph Neural Networks)
    - Langchain
    - Vector Databases
  - category: Data Engineering 
    tools:
    - Oracle
    - SQL Server
    - Apache Kafka
    - Apache Airflow
  - category: Cloud & MLOps
    tools:
    - GCP Big Query / Cloud Storage
    - AWS Lambda / S3
    - Docker
    - CI/CD Pipelines
    - Microservices Architecture
    - RESTful APIs
  - category: Data Visualization & Analytics
    tools:
    - Tableau
    - Power BI
    - Streamlit
  - category: Business & Project Development
    tools:
    - SAP
    - ServiceNow
    - Stakeholder Management
    - Executive Presentations
    - SDLC Management


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   "xeozgvne"



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2c3e50"         
  border: "#a9cfe7"       
  link: "#2980b9"         
  highlight: "#5dade2"    
  background: "#ecf0f1"   
  light_background: "#d6eaf8" 

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

lightblue theme:
  text: "#2c3e50"         
  border: "#a9cfe7"       
  link: "#2980b9"         
  highlight: "#5dade2"    
  background: "#ecf0f1"   
  light_background: "#d6eaf8" 






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
